# Generated by Django 5.0 on 2024-01-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link above to Read Blog Post ...', max_length=255),
        ),
    ]
